Runner: fix crash on error path
Fix a crash with the following symptoms:

  File "statscollectlibs/Runner.py", line 57, in close
    if self._proc.poll() is None:
       ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'poll'

Signed-off-by: Artem Bityutskiy <artem.bityutskiy@linux.intel.com>